"""Contracts shared by the desktop, server, and vision code."""

from .derivatives import (
    DERIVATIVE_PROFILE,
    DERIVATIVE_PROFILE_ID,
    DERIVATIVE_VARIANTS,
    MAX_WATERMARK_TEXT_LENGTH,
    WATERMARK_RENDERER_ID,
    AssetDerivativesInput,
    AssetVariant,
    DerivativeObjectInput,
    DerivativeProfile,
    DerivativeVariant,
    DerivativeVariantProfile,
    PreviewPolicyInput,
    WatermarkLogoKind,
    WatermarkTemplate,
    normalized_watermark_text,
)
from .events import EventSnapshot, PreviewPolicySnapshot, SubEventSnapshot
from .ingestion import ContractError, ContributionInput, OriginalAssetInput
from .states import (
    ContributionState,
    EventState,
    IngestionManifestState,
    InstallationStatus,
    IntakeState,
    UploadObjectState,
    can_transition_event,
)

__all__ = [
    "AssetDerivativesInput",
    "AssetVariant",
    "DERIVATIVE_PROFILE",
    "DERIVATIVE_PROFILE_ID",
    "DERIVATIVE_VARIANTS",
    "DerivativeProfile",
    "DerivativeObjectInput",
    "DerivativeVariant",
    "DerivativeVariantProfile",
    "ContributionState",
    "ContributionInput",
    "ContractError",
    "InstallationStatus",
    "EventState",
    "EventSnapshot",
    "IngestionManifestState",
    "IntakeState",
    "MAX_WATERMARK_TEXT_LENGTH",
    "OriginalAssetInput",
    "PreviewPolicyInput",
    "PreviewPolicySnapshot",
    "SubEventSnapshot",
    "UploadObjectState",
    "WATERMARK_RENDERER_ID",
    "WatermarkLogoKind",
    "WatermarkTemplate",
    "can_transition_event",
    "normalized_watermark_text",
]
