"""Contracts shared by the desktop, server, and vision code."""

from .derivatives import (
    DERIVATIVE_PROFILE_ID,
    MAX_WATERMARK_TEXT_LENGTH,
    WATERMARK_RENDERER_ID,
    AssetDerivativesInput,
    DerivativeObjectInput,
    DerivativeVariant,
    OriginalDownloadPolicy,
    PreviewPolicyInput,
    WatermarkLogoKind,
    WatermarkTemplate,
    normalized_watermark_text,
)
from .ingestion import ContractError, ContributionInput, OriginalAssetInput
from .states import (
    AssetState,
    ContributionState,
    DeviceRole,
    DeviceStatus,
    EventState,
    IngestionManifestState,
    IntakeState,
    UploadObjectState,
    can_transition_asset,
    can_transition_event,
)

__all__ = [
    "AssetDerivativesInput",
    "AssetState",
    "DERIVATIVE_PROFILE_ID",
    "DerivativeObjectInput",
    "DerivativeVariant",
    "ContributionState",
    "ContributionInput",
    "ContractError",
    "DeviceRole",
    "DeviceStatus",
    "EventState",
    "IngestionManifestState",
    "IntakeState",
    "MAX_WATERMARK_TEXT_LENGTH",
    "OriginalAssetInput",
    "OriginalDownloadPolicy",
    "PreviewPolicyInput",
    "UploadObjectState",
    "WATERMARK_RENDERER_ID",
    "WatermarkLogoKind",
    "WatermarkTemplate",
    "can_transition_asset",
    "can_transition_event",
    "normalized_watermark_text",
]
