# Generated by Django 5.2.17 on 2026-09-10.

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import openfotos_server.events.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Photographer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=63,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Use a lowercase DNS label containing letters, digits, "
                                    "or hyphens."
                                ),
                                regex=r"^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$",
                            )
                        ],
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("display_name", "slug")},
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "public_token",
                    models.CharField(
                        default=openfotos_server.events.models.generate_event_token,
                        editable=False,
                        max_length=48,
                        unique=True,
                    ),
                ),
                ("pin_hash", models.CharField(editable=False, max_length=256)),
                (
                    "visitor_access_version",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("review", "Review"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("storage_limit_bytes", models.PositiveBigIntegerField(default=25_000_000_000)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="events.photographer",
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("photographer.created", "Photographer created"),
                            ("photographer.changed", "Photographer changed"),
                            ("membership.created", "Membership created"),
                            ("membership.changed", "Membership changed"),
                            ("event.created", "Event created"),
                            ("event.changed", "Event changed"),
                            ("event.state_changed", "Event state changed"),
                            ("event.pin_changed", "Event PIN changed"),
                            ("event.token_changed", "Event token changed"),
                            ("event.access_revoked", "Event access revoked"),
                            ("photographer.login", "Photographer login"),
                            ("photographer.logout", "Photographer logout"),
                            ("event.pin_unlock", "Event PIN unlock"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("denied", "Denied"),
                            ("rate_limited", "Rate limited"),
                        ],
                        max_length=16,
                    ),
                ),
                ("client_hash", models.CharField(blank=True, max_length=64)),
                ("request_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="openfotos_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="events.event",
                    ),
                ),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="events.photographer",
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="PhotographerMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("photographer", "Photographer")],
                        default="photographer",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="events.photographer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photographer_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("photographer__display_name", "user__username")},
        ),
        migrations.CreateModel(
            name="RateLimitBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("photographer_login", "Photographer login"),
                            ("event_pin", "Event PIN"),
                        ],
                        max_length=32,
                    ),
                ),
                ("subject_hash", models.CharField(max_length=64)),
                ("client_hash", models.CharField(max_length=64)),
                ("window_started_at", models.DateTimeField()),
                ("failures", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("purpose", "subject_hash", "client_hash", "window_started_at"),
                        name="unique_rate_limit_window",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=~models.Q(state="published") | models.Q(expires_at__isnull=False),
                name="published_event_has_expiry",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["photographer", "-created_at"],
                name="audit_tenant_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["event", "-created_at"], name="audit_event_time_idx"),
        ),
        migrations.AddConstraint(
            model_name="photographermembership",
            constraint=models.UniqueConstraint(
                fields=("photographer", "user"),
                name="unique_photographer_membership",
            ),
        ),
    ]
