# Generated by Django 5.2.17 on 2026-09-11 09:57

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("original_filename", models.CharField(max_length=255)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                (
                    "sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContributionBatch",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("intake_generation", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("complete", "Complete"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="reserved",
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100)),
                ("processing_profile_id", models.CharField(max_length=100)),
                ("declared_asset_count", models.PositiveIntegerField()),
                ("declared_original_bytes", models.PositiveBigIntegerField()),
                (
                    "manifest_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UploaderDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("installation_id", models.UUIDField()),
                ("label", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[("lead", "Lead"), ("uploader", "Uploader")], max_length=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("revoked", "Revoked")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("last_active_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UploaderInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "max_redemptions",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("redemption_count", models.PositiveSmallIntegerField(default=0, editable=False)),
                ("revoked_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("closed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="derivatives_ready_generation",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="intake_generation",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="event",
            name="intake_state",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")],
                default="open",
                editable=False,
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="max_contribution_devices",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="processing_profile_id",
            field=models.CharField(default="pilot-profile-v1", max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="reserved_original_bytes",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="event",
            name="verified_original_bytes",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("photographer.created", "Photographer created"),
                    ("photographer.changed", "Photographer changed"),
                    ("membership.created", "Membership created"),
                    ("membership.changed", "Membership changed"),
                    ("event.created", "Event created"),
                    ("event.changed", "Event changed"),
                    ("event.state_changed", "Event state changed"),
                    ("event.pin_changed", "Event PIN changed"),
                    ("event.token_changed", "Event token changed"),
                    ("event.access_revoked", "Event access revoked"),
                    ("photographer.login", "Photographer login"),
                    ("photographer.logout", "Photographer logout"),
                    ("event.pin_unlock", "Event PIN unlock"),
                    ("desktop.login", "Desktop login"),
                    ("desktop.token_refresh", "Desktop token refresh"),
                    ("uploader_invitation.created", "Uploader invitation created"),
                    ("uploader_invitation.redeemed", "Uploader invitation redeemed"),
                    ("uploader_invitation.revoked", "Uploader invitation revoked"),
                    ("uploader_device.revoked", "Uploader device revoked"),
                    ("contribution.reserved", "Contribution reserved"),
                    ("contribution.cancelled", "Contribution cancelled"),
                    ("asset_upload.verified", "Asset upload verified"),
                    ("asset.excluded", "Asset excluded"),
                    ("event.intake_closed", "Event intake closed"),
                    ("event.intake_reopened", "Event intake reopened"),
                    ("event.ingestion_finalized", "Event ingestion finalized"),
                ],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="AssetObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("originals", "Original"),
                            ("previews", "Preview"),
                            ("thumbnails", "Thumbnail"),
                        ],
                        max_length=16,
                    ),
                ),
                ("object_key", models.CharField(max_length=255, unique=True)),
                ("expected_bytes", models.PositiveBigIntegerField()),
                (
                    "content_md5",
                    models.CharField(
                        max_length=24,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9+/]{22}==$", "Enter a base64-encoded MD5 digest."
                            )
                        ],
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                            ("excluded", "Excluded"),
                        ],
                        default="reserved",
                        max_length=16,
                    ),
                ),
                ("etag", models.CharField(blank=True, max_length=128)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("excluded_reason", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variant_objects",
                        to="events.asset",
                    ),
                ),
                (
                    "excluded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="excluded_asset_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="events.contributionbatch",
            ),
        ),
        migrations.CreateModel(
            name="DesktopSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("installation_id", models.UUIDField()),
                ("access_token_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("access_expires_at", models.DateTimeField()),
                (
                    "refresh_token_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "previous_refresh_token_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("refresh_expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="desktop_sessions",
                        to="events.photographer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="openfotos_desktop_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor_key", models.CharField(max_length=80)),
                ("key", models.UUIDField()),
                ("operation", models.CharField(max_length=80)),
                (
                    "request_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("response_status", models.PositiveSmallIntegerField()),
                ("response_body", models.JSONField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [models.Index(fields=["expires_at"], name="idempotency_expiry_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("actor_key", "key"), name="unique_actor_idempotency_key"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IngestionManifest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("generation", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[("prepared", "Prepared"), ("committed", "Committed")],
                        default="prepared",
                        max_length=16,
                    ),
                ),
                ("object_key", models.CharField(max_length=255, unique=True)),
                (
                    "content_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("document", models.JSONField()),
                ("asset_count", models.PositiveIntegerField()),
                ("original_bytes", models.PositiveBigIntegerField()),
                ("excluded_asset_count", models.PositiveIntegerField(default=0)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingestion_manifests",
                        to="events.event",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="current_ingestion_manifest",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_for_events",
                to="events.ingestionmanifest",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_contribution_devices__gte", 1), ("max_contribution_devices__lte", 10)
                ),
                name="event_device_limit_between_1_and_10",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("verified_original_bytes__lte", models.F("reserved_original_bytes"))
                ),
                name="event_verified_bytes_within_reserved",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reserved_original_bytes__lte", models.F("storage_limit_bytes"))
                ),
                name="event_reserved_bytes_within_limit",
            ),
        ),
        migrations.AddField(
            model_name="uploaderdevice",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploader_devices",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="desktopsession",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="events.uploaderdevice",
            ),
        ),
        migrations.AddField(
            model_name="contributionbatch",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contribution_batches",
                to="events.uploaderdevice",
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="uploader_device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_events",
                to="events.uploaderdevice",
            ),
        ),
        migrations.AddField(
            model_name="uploaderinvitation",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_uploader_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="uploaderinvitation",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploader_invitations",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="uploaderdevice",
            name="invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="events.uploaderinvitation",
            ),
        ),
        migrations.AddIndex(
            model_name="assetobject",
            index=models.Index(fields=["state"], name="object_state_idx"),
        ),
        migrations.AddConstraint(
            model_name="assetobject",
            constraint=models.UniqueConstraint(
                fields=("asset", "variant"), name="unique_asset_variant"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["batch"], name="asset_batch_idx"),
        ),
        migrations.AddConstraint(
            model_name="ingestionmanifest",
            constraint=models.UniqueConstraint(
                fields=("event", "generation"), name="unique_event_manifest_generation"
            ),
        ),
        migrations.AddConstraint(
            model_name="desktopsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("device__isnull", True)),
                    models.Q(("user__isnull", True), ("device__isnull", False)),
                    _connector="OR",
                ),
                name="desktop_session_has_one_actor",
            ),
        ),
        migrations.AddIndex(
            model_name="contributionbatch",
            index=models.Index(
                fields=["device", "intake_generation", "state"], name="batch_device_gen_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploaderinvitation",
            index=models.Index(fields=["event", "expires_at"], name="invite_event_expiry_idx"),
        ),
        migrations.AddConstraint(
            model_name="uploaderinvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_redemptions__gte", 1), ("max_redemptions__lte", 10)),
                name="invitation_redemptions_between_1_and_10",
            ),
        ),
        migrations.AddConstraint(
            model_name="uploaderinvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("redemption_count__lte", models.F("max_redemptions"))),
                name="invitation_redemptions_within_limit",
            ),
        ),
        migrations.AddIndex(
            model_name="uploaderdevice",
            index=models.Index(fields=["event", "status"], name="device_event_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="uploaderdevice",
            constraint=models.UniqueConstraint(
                fields=("event", "installation_id"), name="unique_event_installation"
            ),
        ),
    ]
