# Generated by Django 5.2.17 on 2026-09-12

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_original_object_metadata(apps, schema_editor):
    AssetObject = apps.get_model("events", "AssetObject")
    for object_record in AssetObject.objects.select_related("asset").iterator():
        object_record.sha256 = object_record.asset.sha256
        object_record.width = object_record.asset.width
        object_record.height = object_record.asset.height
        object_record.save(update_fields=("sha256", "width", "height"))


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_asset_contributionbatch_uploaderdevice_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="captured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="gallery_excluded_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="gallery_excluded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gallery_excluded_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="gallery_exclusion_reason",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="asset",
            name="gallery_position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="derivative_attempt_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="asset",
            name="derivative_failure_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="derivative_failure_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="assetobject",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetobject",
            name="sha256",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="assetobject",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(populate_original_object_metadata, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="assetobject",
            name="height",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="assetobject",
            name="sha256",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="assetobject",
            name="width",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name="event",
            name="original_download_policy",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled"),
                    ("authorized-visitors", "Authorized Visitors"),
                    ("explicit-shares", "Explicit Shares"),
                ],
                default="disabled",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("photographer.created", "Photographer created"),
                    ("photographer.changed", "Photographer changed"),
                    ("membership.created", "Membership created"),
                    ("membership.changed", "Membership changed"),
                    ("event.created", "Event created"),
                    ("event.changed", "Event changed"),
                    ("event.state_changed", "Event state changed"),
                    ("event.pin_changed", "Event PIN changed"),
                    ("event.token_changed", "Event token changed"),
                    ("event.access_revoked", "Event access revoked"),
                    ("photographer.login", "Photographer login"),
                    ("photographer.logout", "Photographer logout"),
                    ("event.pin_unlock", "Event PIN unlock"),
                    ("desktop.login", "Desktop login"),
                    ("desktop.token_refresh", "Desktop token refresh"),
                    ("uploader_invitation.created", "Uploader invitation created"),
                    ("uploader_invitation.redeemed", "Uploader invitation redeemed"),
                    ("uploader_invitation.revoked", "Uploader invitation revoked"),
                    ("uploader_device.revoked", "Uploader device revoked"),
                    ("contribution.reserved", "Contribution reserved"),
                    ("contribution.cancelled", "Contribution cancelled"),
                    ("asset_upload.verified", "Asset upload verified"),
                    ("asset.excluded", "Asset excluded"),
                    ("event.intake_closed", "Event intake closed"),
                    ("event.intake_reopened", "Event intake reopened"),
                    ("event.ingestion_finalized", "Event ingestion finalized"),
                    ("preview_policy.confirmed", "Preview policy confirmed"),
                    ("derivative_upload.verified", "Derivative upload verified"),
                    ("derivative.failed", "Derivative failed"),
                    ("asset.gallery_excluded", "Asset excluded from gallery"),
                    ("asset.gallery_restored", "Asset restored to gallery"),
                    ("event.download_policy_changed", "Download policy changed"),
                ],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="PreviewPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("compact-bottom-right", "Compact Bottom Right"),
                            ("bottom-center", "Bottom Center"),
                            ("center-brand", "Center Brand"),
                            ("repeated-diagonal", "Repeated Diagonal"),
                        ],
                        default="compact-bottom-right",
                        max_length=32,
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=60)),
                (
                    "logo_kind",
                    models.CharField(
                        choices=[("none", "NONE"), ("ofts", "OFTS"), ("custom", "CUSTOM")],
                        default="none",
                        max_length=16,
                    ),
                ),
                (
                    "renderer_id",
                    models.CharField(default="watermark-raster-v1", editable=False, max_length=100),
                ),
                (
                    "derivative_profile_id",
                    models.CharField(default="gallery-jpeg-v1", editable=False, max_length=100),
                ),
                (
                    "mark_object_key",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                (
                    "mark_sha256",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("mark_bytes", models.PositiveIntegerField(default=0)),
                ("mark_width", models.PositiveIntegerField(default=0)),
                ("mark_height", models.PositiveIntegerField(default=0)),
                ("confirmed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_preview_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preview_policy",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(enabled=False, mark_bytes=0, mark_object_key__isnull=True),
                            models.Q(
                                enabled=True,
                                mark_bytes__gt=0,
                                mark_height__gt=0,
                                mark_object_key__isnull=False,
                                mark_width__gt=0,
                            ),
                            _connector="OR",
                        ),
                        name="preview_policy_mark_matches_enabled",
                    )
                ]
            },
        ),
    ]
