# Generated by Django 5.2.17 on 2026-09-16 15:45

import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


def reject_published_events(apps, schema_editor):
    event = apps.get_model("events", "Event")
    if event.objects.using(schema_editor.connection.alias).filter(state="published").exists():
        raise RuntimeError(
            "Session 7 cannot migrate a published event. Unpublish and index it deliberately."
        )


def enable_pgvector(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector")


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_sub_events_and_photographer_installations"),
    ]

    operations = [
        migrations.RunPython(reject_published_events, migrations.RunPython.noop),
        migrations.RunPython(enable_pgvector, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("photographer.created", "Photographer created"),
                    ("photographer.changed", "Photographer changed"),
                    ("membership.created", "Membership created"),
                    ("membership.changed", "Membership changed"),
                    ("event.created", "Event created"),
                    ("event.changed", "Event changed"),
                    ("event.state_changed", "Event state changed"),
                    ("event.pin_changed", "Event PIN changed"),
                    ("event.token_changed", "Event token changed"),
                    ("event.access_revoked", "Event access revoked"),
                    ("photographer.login", "Photographer login"),
                    ("photographer.logout", "Photographer logout"),
                    ("event.pin_unlock", "Event PIN unlock"),
                    ("desktop.login", "Desktop login"),
                    ("desktop.token_refresh", "Desktop token refresh"),
                    ("sub_event.created", "Sub-event created"),
                    ("sub_event.changed", "Sub-event changed"),
                    ("sub_event.archived", "Sub-event archived"),
                    ("sub_event.restored", "Sub-event restored"),
                    ("event_installation.registered", "Event installation registered"),
                    ("event_installation.revoked", "Event installation revoked"),
                    ("contribution.reserved", "Contribution reserved"),
                    ("contribution.reassigned", "Contribution reassigned"),
                    ("contribution.cancelled", "Contribution cancelled"),
                    ("asset_upload.verified", "Asset upload verified"),
                    ("asset.excluded", "Asset excluded"),
                    ("event.intake_closed", "Event intake closed"),
                    ("event.intake_reopened", "Event intake reopened"),
                    ("event.ingestion_finalized", "Event ingestion finalized"),
                    ("preview_policy.confirmed", "Preview policy confirmed"),
                    ("derivative_upload.verified", "Derivative upload verified"),
                    ("derivative.failed", "Derivative failed"),
                    ("face_analysis.completed", "Face analysis completed"),
                    ("face_analysis.failed", "Face analysis failed"),
                    ("face_analysis.conflict", "Face analysis conflicted"),
                    ("face_analysis.reset", "Face analysis reset"),
                    ("asset.gallery_excluded", "Asset excluded from gallery"),
                    ("asset.gallery_restored", "Asset restored to gallery"),
                ],
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="face_index_ready_generation",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="face_model_id",
            field=models.CharField(
                default="opencv-yunet-2023mar-sface-2021dec", editable=False, max_length=128
            ),
        ),
        migrations.CreateModel(
            name="FaceAnalysis",
            fields=[
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="face_analysis",
                        serialize=False,
                        to="events.asset",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                            ("conflict", "Conflict"),
                            ("indexed", "Indexed"),
                            ("no_usable_face", "No usable face"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "source_sha256",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("model_id", models.CharField(max_length=128)),
                ("artifact_sha256", models.JSONField(default=list)),
                (
                    "document_sha256",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("detected_face_count", models.PositiveSmallIntegerField(default=0)),
                ("usable_face_count", models.PositiveSmallIntegerField(default=0)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("completed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("detected_face_count__gte", models.F("usable_face_count"))
                        ),
                        name="face_detected_count_covers_usable",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("failure_code", ""),
                                ("state", "indexed"),
                                ("usable_face_count__gt", 0),
                            ),
                            models.Q(
                                ("failure_code", ""),
                                ("state", "no_usable_face"),
                                ("usable_face_count", 0),
                            ),
                            models.Q(
                                ("state__in", ("pending", "failed", "conflict")),
                                ("usable_face_count", 0),
                            ),
                            _connector="OR",
                        ),
                        name="face_analysis_state_matches_counts",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FaceEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("face_ordinal", models.PositiveSmallIntegerField()),
                ("detector_confidence", models.FloatField()),
                ("bounding_box_width", models.PositiveIntegerField()),
                ("bounding_box_height", models.PositiveIntegerField()),
                ("model_id", models.CharField(max_length=128)),
                ("vector", pgvector.django.vector.VectorField(dimensions=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="events.faceanalysis",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="face_embeddings",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["event", "model_id"], name="face_event_model_idx"),
                    models.Index(fields=["analysis"], name="face_analysis_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("analysis", "face_ordinal"), name="unique_analysis_face_ordinal"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("detector_confidence__gte", 0.0), ("detector_confidence__lte", 1.0)
                        ),
                        name="face_confidence_between_zero_and_one",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("bounding_box_width__gt", 0), ("bounding_box_height__gt", 0)
                        ),
                        name="face_box_dimensions_positive",
                    ),
                ],
            },
        ),
    ]
