# Generated by Django 5.2.17 on 2026-09-18 05:14

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_face_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="pin_hash",
        ),
        migrations.RemoveField(
            model_name="event",
            name="public_token",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="visitor_access_version",
            new_name="share_access_version",
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("photographer.created", "Photographer created"),
                    ("photographer.changed", "Photographer changed"),
                    ("membership.created", "Membership created"),
                    ("membership.changed", "Membership changed"),
                    ("event.created", "Event created"),
                    ("event.changed", "Event changed"),
                    ("event.state_changed", "Event state changed"),
                    ("photographer.login", "Photographer login"),
                    ("photographer.logout", "Photographer logout"),
                    ("owner_capability.issued", "Owner capability issued"),
                    ("owner_capability.revoked", "Owner capability revoked"),
                    ("owner_capability.pin_unlock", "Owner PIN unlock"),
                    ("guest_capability.created", "Guest capability created"),
                    ("guest_capability.revoked", "Guest capability revoked"),
                    ("guest_capability.pin_unlock", "Guest PIN unlock"),
                    ("share_access.reset", "Share access reset"),
                    ("face_search.completed", "Face search completed"),
                    ("face_search.rejected", "Face search rejected"),
                    ("original_download.issued", "Original download issued"),
                    ("desktop.login", "Desktop login"),
                    ("desktop.token_refresh", "Desktop token refresh"),
                    ("sub_event.created", "Sub-event created"),
                    ("sub_event.changed", "Sub-event changed"),
                    ("sub_event.archived", "Sub-event archived"),
                    ("sub_event.restored", "Sub-event restored"),
                    ("event_installation.registered", "Event installation registered"),
                    ("event_installation.revoked", "Event installation revoked"),
                    ("contribution.reserved", "Contribution reserved"),
                    ("contribution.reassigned", "Contribution reassigned"),
                    ("contribution.cancelled", "Contribution cancelled"),
                    ("asset_upload.verified", "Asset upload verified"),
                    ("asset.excluded", "Asset excluded"),
                    ("event.intake_closed", "Event intake closed"),
                    ("event.intake_reopened", "Event intake reopened"),
                    ("event.ingestion_finalized", "Event ingestion finalized"),
                    ("preview_policy.confirmed", "Preview policy confirmed"),
                    ("derivative_upload.verified", "Derivative upload verified"),
                    ("derivative.failed", "Derivative failed"),
                    ("face_analysis.completed", "Face analysis completed"),
                    ("face_analysis.failed", "Face analysis failed"),
                    ("face_analysis.conflict", "Face analysis conflicted"),
                    ("face_analysis.reset", "Face analysis reset"),
                    ("asset.gallery_excluded", "Asset excluded from gallery"),
                    ("asset.gallery_restored", "Asset restored to gallery"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="ratelimitbucket",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("photographer_login", "Photographer login"),
                    ("owner_pin", "Owner PIN"),
                    ("guest_pin", "Guest PIN"),
                    ("face_search_client", "Face search by client"),
                    ("face_search_capability", "Face search by capability"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="OwnerCapability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "secret_digest",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("pin_hash", models.CharField(editable=False, max_length=256)),
                ("access_version", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_openfotos_owner_capabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_capability",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GuestCapability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "secret_digest",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("pin_hash", models.CharField(editable=False, max_length=256)),
                ("access_version", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(blank=True, max_length=80)),
                (
                    "sub_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_capabilities",
                        to="events.subevent",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_capabilities",
                        to="events.ownercapability",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="FaceSearchResultSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ordered_asset_ids", models.JSONField(default=list)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_search_results",
                        to="events.event",
                    ),
                ),
                (
                    "sub_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_search_results",
                        to="events.subevent",
                    ),
                ),
                (
                    "guest_capability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_search_results",
                        to="events.guestcapability",
                    ),
                ),
                (
                    "owner_capability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_search_results",
                        to="events.ownercapability",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["expires_at"], name="face_search_expiry_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("guest_capability__isnull", True),
                                ("owner_capability__isnull", False),
                            ),
                            models.Q(
                                ("guest_capability__isnull", False),
                                ("owner_capability__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="face_search_has_one_capability",
                    )
                ],
            },
        ),
    ]
