# Generated by Django 5.2.17 on 2026-09-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0013_single_event_portal_and_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("photographer.created", "Photographer created"),
                    ("photographer.changed", "Photographer changed"),
                    ("membership.created", "Membership created"),
                    ("membership.changed", "Membership changed"),
                    ("event.created", "Event created"),
                    ("event.changed", "Event changed"),
                    ("event.state_changed", "Event state changed"),
                    ("portfolio.profile_changed", "Portfolio profile changed"),
                    ("portal_capability.issued", "Portfolio PIN issued"),
                    ("portal_capability.rotated", "Portfolio PIN rotated"),
                    ("portal_capability.pin_unlock", "Portfolio PIN unlock"),
                    ("event.media_purged", "Event media purged"),
                    ("photographer.login", "Photographer login"),
                    ("photographer.logout", "Photographer logout"),
                    ("share_access.reset", "Share access reset"),
                    ("face_search.completed", "Face search completed"),
                    ("face_search.rejected", "Face search rejected"),
                    ("original_download.issued", "Original download issued"),
                    ("desktop.login", "Desktop login"),
                    ("desktop.logout", "Desktop sign out"),
                    ("desktop.token_refresh", "Desktop token refresh"),
                    ("sub_event.created", "Sub-event created"),
                    ("sub_event.changed", "Sub-event changed"),
                    ("sub_event.archived", "Sub-event archived"),
                    ("sub_event.restored", "Sub-event restored"),
                    ("event_installation.registered", "Event installation registered"),
                    ("event_installation.revoked", "Event installation revoked"),
                    ("contribution.reserved", "Contribution reserved"),
                    ("contribution.reassigned", "Contribution reassigned"),
                    ("contribution.cancelled", "Contribution cancelled"),
                    ("asset_upload.verified", "Asset upload verified"),
                    ("asset.excluded", "Asset excluded"),
                    ("event.intake_closed", "Event intake closed"),
                    ("event.intake_reopened", "Event intake reopened"),
                    ("event.ingestion_finalized", "Event ingestion finalized"),
                    ("event.publication_snapshot", "Event publication snapshot committed"),
                    ("preview_policy.confirmed", "Preview policy confirmed"),
                    ("derivative_upload.verified", "Derivative upload verified"),
                    ("derivative.failed", "Derivative failed"),
                    ("face_analysis.completed", "Face analysis completed"),
                    ("face_analysis.failed", "Face analysis failed"),
                    ("face_analysis.conflict", "Face analysis conflicted"),
                    ("face_analysis.reset", "Face analysis reset"),
                    ("asset.gallery_excluded", "Asset excluded from gallery"),
                    ("asset.gallery_restored", "Asset restored to gallery"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="previewpolicy",
            name="logo_kind",
            field=models.CharField(
                choices=[("none", "NONE"), ("onenodeai", "ONENODEAI"), ("custom", "CUSTOM")],
                default="none",
                max_length=16,
            ),
        ),
    ]
